### ISSUE TITLE
in jQuery.event.frame.js handle is deprecated in jQuery 1.9

### ISSUE THREAD

**Issue by charleslouis** [stephband/jparallax#63]
Hi!

It seems that "handle" is deprecated and no longer used in Jquery 1.9. Hence it returns undefined in event.frame. As I have read, it is just an alias that has been removed.

Replacing it with dispatch will ensure compatibility with jQuery 1.9 (at least it is working for me)/

Line 101 of event.frame.js:

``` js
jQuery.event.handle.apply(this, arguments);
```

should now be

``` js
jQuery.event.dispatch.apply(this, arguments);
```

Thanks !

**Comment by dragoeco** [comment]
Works with jQuery 1.11.2 as well.
Thanks a lot
